version: "3.9"

services:
  api:
    container_name: api_imemes
    build: .
    ports:
      - 4242:4242
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app

  db:
    container_name: db_imemes
    image: postgres:14.3-alpine
    ports:
      - 5430:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=imemes_database
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d imemes_database"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
    volumes:
      - ./create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
      - db_psql_memes:/var/lib/postgresql/data

volumes:
  db_psql_memes:
    driver: local
